# Generated by Django 3.2.7 on 2021-09-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserveflats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserveflats',
            options={'verbose_name': 'квартиру', 'verbose_name_plural': 'квартиры'},
        ),
        migrations.RemoveField(
            model_name='reserveflats',
            name='num_flat',
        ),
        migrations.AlterField(
            model_name='reserveflats',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер квартиры'),
        ),
        migrations.AlterField(
            model_name='reserveflats',
            name='price',
            field=models.FloatField(verbose_name='Цена квартиры ($)'),
        ),
        migrations.AlterField(
            model_name='reserveflats',
            name='reserved',
            field=models.BooleanField(verbose_name='Резерв'),
        ),
    ]
