# Generated by Django 3.2.7 on 2021-10-03 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserveflats', '0004_stripepayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripePayment',
        ),
    ]
