# Generated by Django 3.2.7 on 2021-10-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserveflats', '0005_delete_stripepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
