# Generated by Django 3.2.7 on 2021-10-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserveflats', '0006_stripepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessPaymentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя покупателя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия покупателя')),
                ('email', models.EmailField(max_length=255, verbose_name='Email покупателя')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон покупателя')),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
